Web/FrontEnd/Controllers/contactUsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Yara.Blog.Web.FrontEnd.MVC_EF_CodeFirst.Models;

namespace Yara.Blog.Web.FrontEnd.Controllers
{
    public class contactUsController : Controller
    {
        //
        // GET: /contactUs/
        MVC_EF_CF_DB _db ;
        public contactUsController()
        {
            _db = new MVC_EF_CF_DB();
        }

        public ActionResult List() 
        {
            return PartialView("contactList", _db.contacts.ToList());
        }
        //
        // GET: /contactUs/Create
        [HttpGet]
        public ActionResult Create()
        {
            contactUs cu = new contactUs();
            return View(cu);
        } 

        //
        // POST: /contactUs/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here
                contactUs cu = new contactUs()
                {
                    //authorID = Convert.ToInt32(Request["authorID"]),
                    comment = Request["comment"],
                    email = Request["email"],
                    name = Request["name"],
                    reason = Request["reason"]
                };
                _db.contacts.Add(cu);
                _db.SaveChanges();

                return RedirectToAction("List");
            }
            catch
            {
                return View();
            }
        }
        
        
    }
}

Web/FrontEnd/Controllers/postController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Yara.Blog.Data;
using Yara.Blog.Domain;
using Yara.Blog.Domain.ViewModels.FrontEnd.PostModels;

namespace Yara.Blog.Web.FrontEnd.Controllers
{
    public class postController : Controller
    {
        private Repository<post> _postRepository;

        public postController()
        {
            _postRepository = new Repository<post>(new BlogDBEntities());
        }

        //
        // GET: /post/
        public ActionResult List()
        {
            var objPosts = _postRepository.GetAll();
            List<PostViewModel> posts = new List<PostViewModel>();
            foreach (var item in objPosts)
            {
                PostViewModel post = new PostViewModel();
                post.postID = item.postID;
                post.Title = item.Title;
                post.Text = item.Text;
                post.authorName = item.author.lastName;
                post.Created = item.Created;
                posts.Add(post);
            }
            return View(posts);
        }
        //
        // GET: /post/Details/5
        //public ActionResult post(int) 
        //{

        //}
        public ActionResult Details(int id)
        {
            post myPost = _postRepository.Get(p => p.postID == id);
            PostViewModel postView = new PostViewModel()
            {
                authorName = myPost.author.lastName,
                Created =myPost.Created,
                postID = myPost.postID,
                Text = myPost.Text,
                Title = myPost.Title
            };
            return View(postView);
        }
        //
        // GET: /post/Create
        [HttpGet]
        public ActionResult Create()
        {
            var post = new CreateViewModel();
            return View(post);
        }
        //
        // POST: /post/Create
        [HttpPost]
        public ActionResult Create(CreateViewModel post)
        {
            try
            {
                post myPost = new post()
                {
                    Title = post.Title,
                    Text = post.Text,
                    authorID = 1,
                    Created = DateTime.Now,
                };
                _postRepository.Add(myPost);
                _postRepository.Save();
                return RedirectToAction("List");
            }
            catch(Exception ex)
            {
                return View();
            }
        }
        //
        // GET: /post/Edit/5
        [Authorize]
        public ActionResult Edit(int id)
        {
            return View();
        }
        //
        // POST: /post/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("List");
            }
            catch
            {
                return View();
            }
        }
        //
        // GET: /post/Delete/5
        [Authorize]
        public ActionResult Delete(int id)
        {
            return View();
        }
        //
        // POST: /post/Delete/5
        [HttpPost]
        [Authorize]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("List");
            }
            catch
            {
                return View();
            }
        }
    }
}

Web/FrontEnd/Views/Shared/_Layout.cshtml

<!DOCTYPE html>
<!--[if lt IE 7]> <html dir="ltr" lang="en-US" class="no-js lt-ie9 lt-ie8 lt-ie7" > <![endif]-->
<!--[if IE 7]>    <html dir="ltr" lang="en-US" class="no-js ie7 lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>    <html dir="ltr" lang="en-US" class="no-js ie8 lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->

<html dir="rtl" lang="en-US" class="no-js">
<!--<![endif]-->

<head>
    <meta charset="utf-8">

    <title>@ViewBag.Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href='http://fonts.googleapis.com/css?family=Lato:400,700,400italic|Yanone+Kaffeesatz' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="@Url.Content("~/Content/style.css")" type="text/css">
    <link rel="stylesheet" href="@Url.Content("~/Content/themes/default.css")" type="text/css">
    <script src="@Url.Content("~/Scripts/modernizr-2.5.3.js")" type="text/javascript"></script>

</head>

<body>

    

    <header id="header">
        <div class="pre-head show-on-mobile">
            <div class="wrap group">
                <div class="pre-head-wgt group">
                    

                    <aside class="widget widget_search group">
                        <form action="/" id="searchform2" class="searchform" method="get" role="search">
                            <input size="27" type="text" title="Search" id="s2" class="s" name="s"> <a id="searchsubmit2" class="searchsubmit"><img src="@Url.Content("~/Content/images/search.png")" alt="GO"></a>
                        </form>
                    </aside>
                </div><!-- .header-wgt -->
            </div>
            
        </div><!-- .pre-head -->

        <div id="site-head">
            <div class="wrap group">
                <hgroup class="logo">
                    <h1><a href=""><img src="@Url.Content("~/Content/images/color-default.png")" alt=""></a></h1>
                </hgroup>

                <div class="header-wgt group">
                    <div id="logindisplay">
                        @Html.Partial("_LogOnPartial")
                    </div>

                    <aside class="widget widget_search group">
                        <form action="/" id="searchform1" class="searchform" method="get" role="search">
                            <input size="27" type="text" title="Search" id="s1" class="s" name="s"> <a id="searchsubmit1" class="searchsubmit"><img src="@Url.Content("~/Content/images/search.png")" alt="GO"></a>
                        </form>
                    </aside>
                </div><!-- .header-wgt -->
            </div><!-- .wrap < #header -->
        </div><!-- #site-head -->

        <nav>
            <div class="wrap group">
                <ul id="navigation" class="group">
                <li>@Html.ActionLink("خانه", "List", "post")</li>
                    <li>
                        <a href="#">Post Formats</a>
                        <ul>
                            <li><a href="">Standard Format</a></li>
                            <li><a href="">Image Format</a></li>
                            <li><a href="">Gallery Format</a></li>
                            <li><a href="">Video Format</a></li>
                            <li><a href="">Audio Format</a></li>
                            <li><a href="">Quote Format</a></li>
                        </ul>
                    </li>
                <li>@Html.ActionLink("تماس با ما", "Create", "contactUs")</li>
                </ul>
            </div><!-- .wrap < nav -->
        </nav>
    </header>

    <div id="page">
        <section id="main">
            <div class="wrap group">
                <div id="box-container">
                    <div id="entry-listing" class="inner-Container full group">
                     <div class="box-hold group">
                        
                      @RenderBody()  
                      
                       
                       </div>
                       
                    </div><!-- #entry-listing -->

                    <div class="nav">
                        <a id="nextpage" href="content1.html">Next Page</a>
                    </div>
                </div>
            </div><!-- .wrap < #main -->
        </section><!--  #main -->

        <footer id="footer">
            <div class="wrap group">
                <div class="footer-text">
                    <a href="#">Myblog</a> &mdash; this is a site.
                </div>
            </div>
        </footer>
    </div><!-- #page -->

    <script src="../../Scripts/jquery-1.7.1.min.js" type="text/javascript"></script>
</body>
</html>
@*
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-1.7.min.js")" type="text/javascript"></script>
</head>
<body>
    <div class="page">
        <header>
            <div id="title">
                <h1>My MVC Application</h1>
            </div>
            <div id="logindisplay">
                @Html.Partial("_LogOnPartial")
            </div>
            <nav>
                <ul id="menu">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                </ul>
            </nav>
        </header>
        <section id="main">
            @RenderBody()
        </section>
        <footer>
        </footer>
    </div>
</body>
</html>
*@

Web/FrontEnd/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Welcome <strong>@User.Identity.Name</strong>!
    [ @Html.ActionLink("Log Off", "LogOff", "Account") ]</text>
}
else {
    @:[ @Html.ActionLink("Log On", "LogOn", "Account") ]
}

Web/FrontEnd/Views/Shared/commentCtrl.cshtml
@model List<Yara.Blog.Domain.ViewModels.FrontEnd.CommentModels.CommentViewModel>
           <ol id="comment-list" class="group">
           @{foreach (var item in Model)
             {
                 <li class="comment">
                 <span class="comment-meta">
                 comment Title:<strong>
                 @item.Title
                 </strong>
                 <time datetime="2012-08-07">
                 </time>
                 <text>---</text>
                 <a class="comment-reply-link" href="">Reply</a>
                 </span>
                 <div class="comment-text group">
               <p>@item.Text</p>
               </div>
               </li>
             }
               }
               </ol>